apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms3-app-server
  namespace: monitor
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: ms3-app-server
  endpoints:
  - port: http
    path: '/actuator/prometheus'
    interval: 5s
  
